language: python
sudo: false
python:
  - "2.7"
  - "3.6"
  - "3.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "pypy"
  # - "pypy-5.3.1"

matrix:
    allow_failures:
        - python: 3.6

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE {{ cookiecutter.app_name }};'

# command to install dependencies
install:
  - python setup.py build sdist
  - pip install -r development.txt

# command to run tests
script: nosetests --verbosity 2 --with-spec --spec-color tests/unit tests/functional

# automated pypi releases
deploy:
  provider: pypi
  user: {{cookiecutter.github_username}}
  password:
    secure: E5KbnpQau7jv/mpHWAs19Y5zBaOHyBXRCGAsTS0S5lEOp/g8EEbjyt5rL7lcIeFAYarIds719BktC5iO+1AQbXOYicS5vDfiVRdLaJ5HPA4v6zyyQzwadFKSqE1Tv11AG9xkFDfBEPLTQmSrpI5cJIY5UoafDnMZe4CbLVETTw8=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
